import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// This package lives at packages/convex-analytics/ inside the monorepo; the
// public docs (README, CHANGELOG, docs/) live at the repo root. Paths are
// resolved against the repo root so `pnpm --filter @vllnt/convex-analytics
// generate:llms` writes the repo-root llms-full.txt.
const repoRoot = resolve(process.cwd(), "../..");
const pkgRoot = process.cwd();

// Repo-root docs bundled verbatim, in order.
const docs = [
  "README.md",
  "CHANGELOG.md",
  "docs/schema.md",
  "docs/client-sdk.md",
  "docs/api-reference.md",
  "docs/web-preset.md",
  "docs/multi-product.md",
  "docs/architecture.md",
  "docs/mcp-tools.md",
];

// Public source files, fenced as TypeScript. Keep in sync with the public surface.
const sources = [
  "src/shared.ts",
  "src/client/types.ts",
  "src/client/index.ts",
  "src/web/index.ts",
  "src/react/index.tsx",
  "src/component/schema.ts",
  "src/component/validators.ts",
  "src/component/mutations.ts",
  "src/component/queries.ts",
  "src/component/internal_mutations.ts",
  "src/component/http.ts",
  "src/test.ts",
];

let out = `# @vllnt/convex-analytics — Full Source\n\nAuto-generated by \`pnpm generate:llms\`. Do not edit manually.\n`;

for (const f of docs) {
  out += `\n---\n\n## ${f}\n\n`;
  out += readFileSync(resolve(repoRoot, f), "utf8");
  out += "\n";
}

for (const f of sources) {
  out += `\n---\n\n## packages/convex-analytics/${f}\n\n`;
  out += "```ts\n" + readFileSync(resolve(pkgRoot, f), "utf8") + "\n```";
  out += "\n";
}

writeFileSync(resolve(repoRoot, "llms-full.txt"), out);
console.log(`Wrote llms-full.txt (${docs.length + sources.length} files)`);
